services:
  web:
    build:
      context: .
    container_name: lanzaudit_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app/static/reports:/app/static/reports

  db:
    image: mariadb:11.3
    container_name: lanzaudit_db
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Madrid
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"

volumes:
  mariadb_data:
