services:
  web:
    build:
      context: .
    container_name: lanzaudit_web
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - static:/app/static
      - reports:/app/reports
      - profile_pics:/app/profile_pics
      

  db:
    image: mariadb:11.3
    container_name: lanzaudit_db
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Madrid
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"

  nginx:
    image: nginx:stable-alpine
    container_name: lanzaudit_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
      - reports:/app/reports
      - profile_pics:/app/profile_pics

volumes:
  mariadb_data:
  static:
  reports:
  profile_pics:
