"""Añadiendo el TTL a la tabla ScanResults

Revision ID: 1d1747696bca
Revises: c9342b419e3b
Create Date: 2025-05-05 10:47:45.899563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1747696bca'
down_revision = 'c9342b419e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ttl', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_column('ttl')

    # ### end Alembic commands ###
