"""Actualizando tabla Scan

Revision ID: 62f92d003376
Revises: 6c1181ba9ba0
Create Date: 2025-04-21 12:26:44.963195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62f92d003376'
down_revision = '6c1181ba9ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('scan_type',
               existing_type=mysql.ENUM('Puertos', 'WordPress'),
               type_=sa.Enum('Nmap', 'WPScan', name='scan_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.alter_column('scan_type',
               existing_type=sa.Enum('Nmap', 'WPScan', name='scan_type_enum'),
               type_=mysql.ENUM('Puertos', 'WordPress'),
               existing_nullable=False)

    # ### end Alembic commands ###
