"""Añadiendo los campos de solicitud de recuperación de contraseña

Revision ID: 6c1181ba9ba0
Revises: e1d39cf328bf
Create Date: 2025-04-04 12:32:17.473985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1181ba9ba0'
down_revision = 'e1d39cf328bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_requested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_requested_at')
        batch_op.drop_column('password_reset_requested')

    # ### end Alembic commands ###
